### ISSUE TITLE
Unpack .Net Hasp Envelope

### ISSUE THREAD

**Issue by nareshn2003** [0xd4d/de4dot#181]
Hi

Actually i want to ask is it possible to do unpacking of .exe that is protected by .net HASP envelope using de4dot  ?

.Net hasp envelope tool hides the code make method to DynamicMethod. It makes codes similar to this

			try
			{
				DynamicMethod dynamicMethod = Class0.smethod_7(null, MethodBase.GetCurrentMethod(), true);
				if (dynamicMethod != null)
				{
					object[] parameters = new object[0];
					dynamicMethod.Invoke(null, parameters);
				}
				Class0.smethod_7(null, MethodBase.GetCurrentMethod(), false);
			}
			catch (Exception ex)
			{
				Exception innerException = ex.InnerException;
				if (innerException == null)
				{
					throw;
				}
				throw innerException;
			}

If we debug the code in DynamicMethod it contains all instruction . I had seen similar tool that doing unpacking using dnlib but Hasp packing has different method.

https://github.com/Michidu/ILUnpacker

Any ideas ? How to implement ?

**Comment by 0xd4d** [comment]
You have to write that code yourself. Analyze it, find an instance of a dynamic method and use dnlib to get back a method that you can save to some assembly.

**Comment by nareshn2003** [comment]
Any idea where to start ? Which class in dnlib to investigate ?

**Comment by sachin0606** [comment]
as i saw the HaspEnvelop is decrypt the string using private key within the hardware lock. so without the lock even you write the program we cant decrypt the string.

**Comment by nareshn2003** [comment]
Decrypt string can be done very easily. Dynamicmethod hides the actual implementation using IL code to somewhere in protect section . It decrypt at runtim and build dynamicMethod from IL. I managed to get IL but could not covert original C# code from IL instructions.

**Comment by SlowLogicBoy** [comment]
As far as I'm aware, Hasp doesn't hide string decryption, everything is present in obfuscated assembly for string decryption, however methods are practically impossible to decrypt without a physical hardware key.
Method binaries are hidden in resources, which are encrypted with quite secure crypto algorythm so it's not even worth trying to brute force them. They are decrypted using native code, using DllImport to hasp library which accesses physical key, I don't quite remember what it sends to hasp:
1. sends whole encrypted binary array and then gets that array decrypted
2. sends 2 seemingly random numbers get's the third one, runs some algorithm which is present in obfuscated assembly to decrypt the method. (those numbers usually are from method metadata)

But my memory is quite funky since I investigated this quite some time ago.
And as far as I remember if you have physical key you can easily get required numbers and deobfuscate it.

**Comment by SlowLogicBoy** [comment]
>I managed to get IL but could not covert original C# code from IL instructions.
you have to replace the method body with those IL instructions you've got.

**Comment by nareshn2003** [comment]
Actually i am getting IL instructions. Not sure how to replace it ?

**Comment by nareshn2003** [comment]
BTW i can share HASP resolver code here not sure about licences terms.

**Comment by SlowLogicBoy** [comment]
right click method name, Edit IL Instructions
